apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: proxmox-name-sync-controller
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
