# Example values for development/testing with username/password authentication

# Controller image (use latest for development)
image:
  repository: your-registry.com/proxmox-name-sync-controller
  tag: "latest"
  pullPolicy: Always

# Development settings
controller:
  leaderElection:
    enabled: false  # Disable for single replica development
  logLevel: debug
  developmentMode: true

# Single replica for development
replicaCount: 1

# Proxmox configuration using username/password (easier for dev/test)
proxmox:
  url: "https://pve-test.local:8006"
  username: "root@pam"
  password: "your-password-here"
  insecure: true  # Accept self-signed certificates in dev

# Lower resource requirements for development
resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

# Enable metrics for testing
metrics:
  enabled: true
  serviceMonitor:
    enabled: false  # Disable if prometheus-operator not available

# Relaxed security for development
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false  # Allow for easier debugging
  runAsNonRoot: true
  capabilities:
    drop:
    - ALL

# No network policy for easier debugging
networkPolicy:
  enabled: false

# Allow scheduling on any node including control plane for testing
tolerations:
- key: node-role.kubernetes.io/control-plane
  operator: Exists
  effect: NoSchedule
