apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "proxmox-name-sync-controller.fullname" . }}
  namespace: {{ include "proxmox-name-sync-controller.namespace" . }}
  labels:
    {{- include "proxmox-name-sync-controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: manager
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "proxmox-name-sync-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "proxmox-name-sync-controller.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "proxmox-name-sync-controller.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      containers:
      - name: manager
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - --metrics-bind-address=0.0.0.0:{{ .Values.metrics.port }}
          - --health-probe-bind-address=0.0.0.0:{{ .Values.healthProbe.port }}
          - --config-path=/config/proxmox.yaml
          {{- if .Values.controller.metricsSecure }}
          - --metrics-secure
          {{- end }}
          {{- if .Values.controller.leaderElection.enabled }}
          - --leader-elect
          {{- end }}
          {{- if .Values.controller.developmentMode }}
          - --zap-devel
          {{- end }}
          {{- if ne .Values.controller.logLevel "info" }}
          - --zap-log-level={{ .Values.controller.logLevel }}
          {{- end }}
        ports:
        - containerPort: {{ .Values.metrics.port }}
          name: metrics
          protocol: TCP
        - containerPort: {{ .Values.healthProbe.port }}
          name: health
          protocol: TCP
        livenessProbe:
          httpGet:
            path: {{ .Values.healthProbe.path }}
            port: health
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.path }}
            port: health
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        envFrom: []
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: proxmox-config
          mountPath: /config
          readOnly: true
      volumes:
      - name: proxmox-config
        secret:
          secretName: {{ include "proxmox-name-sync-controller.secretName" . }}
      restartPolicy: {{ .Values.restartPolicy }}
      terminationGracePeriodSeconds: 10
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
