{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "proxmox-name-sync-controller.fullname" . }}-metrics-service
  namespace: {{ include "proxmox-name-sync-controller.namespace" . }}
  labels:
    {{- include "proxmox-name-sync-controller.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.metrics.service.type }}
  ports:
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "proxmox-name-sync-controller.selectorLabels" . | nindent 4 }}
{{- end }}
