{{- include "proxmox-name-sync-controller.validateProxmox" . }}
{{- if .Values.proxmox.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "proxmox-name-sync-controller.secretName" . }}
  namespace: {{ include "proxmox-name-sync-controller.namespace" . }}
  labels:
    {{- include "proxmox-name-sync-controller.labels" . | nindent 4 }}
type: Opaque
stringData:
  proxmox.yaml: |
    hostUrls:
      - {{ .Values.proxmox.url | quote }}
    {{- if and .Values.proxmox.username .Values.proxmox.password }}
    username: {{ .Values.proxmox.username | quote }}
    password: {{ .Values.proxmox.password | quote }}
    {{- end }}
    {{- if and .Values.proxmox.tokenId .Values.proxmox.secret }}
    tokenId: {{ .Values.proxmox.tokenId | quote }}
    secret: {{ .Values.proxmox.secret | quote }}
    {{- end }}
    insecure: {{ .Values.proxmox.insecure }}
{{- end }}
