{{- include "proxmox-name-sync-controller.validateProxmox" . }}
{{- if and .Values.proxmox.secret.create (not .Values.proxmox.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "proxmox-name-sync-controller.secretName" . }}
  namespace: {{ include "proxmox-name-sync-controller.namespace" . }}
  labels:
    {{- include "proxmox-name-sync-controller.labels" . | nindent 4 }}
type: Opaque
stringData:
  proxmox.yaml: |
    {{- $secret := .Values.proxmox.secret -}}
    {{- if $secret.hostUrls }}
    hostUrls:
    {{- range $secret.hostUrls }}
      - {{ . | quote }}
    {{- end }}
    {{- else if $secret.url }}
    hostUrls:
      - {{ $secret.url | quote }}
    {{- end }}
    {{- if and $secret.username $secret.password }}
    username: {{ $secret.username | quote }}
    password: {{ $secret.password | quote }}
    {{- end }}
    {{- if and $secret.tokenId $secret.secret }}
    tokenId: {{ $secret.tokenId | quote }}
    secret: {{ $secret.secret | quote }}
    {{- end }}
    insecure: {{ $secret.insecure }}
{{- end }}
