{{- include "proxmox-name-sync-controller.validateProxmox" . }}
{{- if .Values.proxmox.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "proxmox-name-sync-controller.secretName" . }}
  namespace: {{ include "proxmox-name-sync-controller.namespace" . }}
  labels:
    {{- include "proxmox-name-sync-controller.labels" . | nindent 4 }}
type: Opaque
stringData:
  PROXMOX_URL: {{ .Values.proxmox.url | quote }}
  {{- if .Values.proxmox.tokenId }}
  PROXMOX_TOKEN_ID: {{ .Values.proxmox.tokenId | quote }}
  {{- end }}
  {{- if .Values.proxmox.secret }}
  PROXMOX_SECRET: {{ .Values.proxmox.secret | quote }}
  {{- end }}
  {{- if .Values.proxmox.username }}
  PROXMOX_USERNAME: {{ .Values.proxmox.username | quote }}
  {{- end }}
  {{- if .Values.proxmox.password }}
  PROXMOX_PASSWORD: {{ .Values.proxmox.password | quote }}
  {{- end }}
  PROXMOX_INSECURE: {{ .Values.proxmox.insecure | quote }}
{{- end }}
