name: Chart Version Check

on:
  pull_request:
    paths:
      - "chart/**"

permissions:
  contents: read
  pull-requests: write

jobs:
  check-chart-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get chart versions
        id: versions
        run: |
          CHART_FILE="chart/proxmox-name-sync-controller/Chart.yaml"
          
          # Get current version from PR
          CURRENT_VERSION=$(grep '^version:' "$CHART_FILE" | awk '{print $2}')
          echo "current_version=${CURRENT_VERSION}" >> "$GITHUB_OUTPUT"
          
          # Get version from main branch
          git fetch origin main:main
          BASE_VERSION=$(git show main:"$CHART_FILE" | grep '^version:' | awk '{print $2}')
          echo "base_version=${BASE_VERSION}" >> "$GITHUB_OUTPUT"
          
          echo "Current chart version: $CURRENT_VERSION"
          echo "Base chart version: $BASE_VERSION"

      - name: Validate version bump
        run: |
          CURRENT="${{ steps.versions.outputs.current_version }}"
          BASE="${{ steps.versions.outputs.base_version }}"
          
          if [[ "$CURRENT" == "$BASE" ]]; then
            echo "❌ ERROR: Chart version must be bumped when making chart changes!"
            echo "Current version: $CURRENT"
            echo "Base version: $BASE"
            echo ""
            echo "Please update the 'version' field in chart/proxmox-name-sync-controller/Chart.yaml"
            echo "Examples:"
            echo "  - Patch change: $BASE -> $(echo $BASE | awk -F. '{print $1"."$2"."($3+1)}')"
            echo "  - Minor change: $BASE -> $(echo $BASE | awk -F. '{print $1"."($2+1)".0"}')"
            echo "  - Major change: $BASE -> $(echo $BASE | awk -F. '{print ($1+1)".0.0"}')"
            exit 1
          else
            echo "✅ Chart version has been properly bumped: $BASE -> $CURRENT"
          fi

      - name: Comment on PR
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const current = '${{ steps.versions.outputs.current_version }}';
            const base = '${{ steps.versions.outputs.base_version }}';
            const patchVersion = base.split('.').map((n, i) => i === 2 ? parseInt(n) + 1 : n).join('.');
            const minorVersion = base.split('.').map((n, i) => i === 1 ? parseInt(n) + 1 : (i === 2 ? 0 : n)).join('.');
            const majorVersion = base.split('.').map((n, i) => i === 0 ? parseInt(n) + 1 : 0).join('.');
            
            const body = `## ❌ Chart Version Check Failed
            
            The chart files have been modified but the chart version was not bumped.
            
            **Current version:** \`${current}\`  
            **Base version:** \`${base}\`
            
            ### Required Action
            Please update the \`version\` field in \`chart/proxmox-name-sync-controller/Chart.yaml\`
            
            ### Suggested versions:
            - **Patch change** (bug fixes): \`${patchVersion}\`
            - **Minor change** (new features): \`${minorVersion}\`
            - **Major change** (breaking changes): \`${majorVersion}\`
            
            ### Example:
            \`\`\`yaml
            apiVersion: v2
            name: proxmox-name-sync-controller
            version: ${patchVersion}  # <- Update this line
            \`\`\``;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
